---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  namespace: bw-account
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/aprabh/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb-claim
  name: influxdb-claim
  namespace: bw-account
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 10Gi

