---
# Service Kafka
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: bw-account
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 31093
      protocol: TCP
    - name: prom-kalfa
      port: 9308
      targetPort: 9308
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: bw-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: '9308'
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181,zookeeper-2:2181
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_CREATE_TOPICS
              value: bwaccount:1:1
            - name: KAFKA_CONNECTIONS_MAX_IDLE_MS
              value: "-1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://10.85.47.165:31093"
          ports:
            - containerPort: 9092
            - containerPort: 9308
      restartPolicy: Always
