---
# Zookeeper service-1
apiVersion: v1
kind: Service
metadata:
 labels:
   app: zookeeper
 name: zookeeper
 namespace: bw-account
spec:
 ports:
 - name: zookeeper-cluster
   port: 2181
   targetPort: 2181
 - name: zookeeper-follower
   protocol: TCP
   port: 2888
   targetPort: 2888
 - name: zookeeper-leader
   protocol: TCP
   port: 3888
   targetPort: 3888
 selector:
   app: zookeeper
---
# Zookeeper service-2
apiVersion: v1
kind: Service
metadata:
 labels:
   app: zookeeper-2
 name: zookeeper-2
 namespace: bw-account
spec:
 ports:
 - name: zookeeper-cluster
   port: 2181
   targetPort: 2181
 - name: zookeeper-follower
   protocol: TCP
   port: 2888
   targetPort: 2888
 - name: zookeeper-leader
   protocol: TCP
   port: 3888
   targetPort: 3888
 selector:
   app: zookeeper-2
---
# Zookeeper Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bw-account
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
      - image: wurstmeister/zookeeper:latest
        imagePullPolicy: Never
        name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2
      restartPolicy: Always
---
# Zookeeper Deploy-2
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bw-account
  labels:
    app: zookeeper-2
  name: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper-2
    spec:
      containers:
      - image: wurstmeister/zookeeper:latest
        imagePullPolicy: Never
        name: zookeeper-2
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_SERVER_2
          value: zookeeper-2
      restartPolicy: Always
---
